# Hackathon Artemisia Elas+ Tech
## Sistema Inteligente de Previsão de Churn Bancário

### Objetivo do Notebook

Este notebook tem como objetivo realizar a ingestão e persistência dos dados do dataset Bank Customer Churn, integrando Python e PostgreSQL para construção da pipeline inicial do projeto.

As etapas contemplam:
- importação das Bibliotecas;
- conexão com PostgreSQL;
- criação automatizada do banco;
- leitura do dataset;
- ingestão dos dados;
- execução de consultas SQL analíticas.

## Importação das Bibliotecas

Nesta etapa são importadas as bibliotecas responsáveis pela manipulação de dados e integração com o banco PostgreSQL.

In [19]:
import os
from sqlalchemy import create_engine, text
import pandas as pd

## Conexão com PostgreSQL

Foi realizada a conexão entre o Python e o PostgreSQL utilizando SQLAlchemy, permitindo automatizar a criação do banco e ingestão dos dados.

In [23]:
senha = os.getenv("POSTGRES_PASSWORD")

In [24]:
engine = create_engine(
    f"postgresql+psycopg2://postgres:{senha}@localhost:5432/postgres"
)

## Criação Automatizada do Banco de Dados

O banco churn_db foi criado diretamente pelo notebook utilizando comandos SQL executados via Python.

In [18]:
with engine.connect() as conn:
    conn.execute(text("COMMIT"))

    try:
        conn.execute(text("CREATE DATABASE churn_db"))
        print("Banco criado com sucesso!")

    except:
        print("Banco já existe.")

Banco já existe.

In [22]:
engine = create_engine(
    f"postgresql+psycopg2://postgres:{senha}@localhost:5432/churn_db"
)

## Leitura do Dataset

O dataset Bank Customer Churn foi carregado para análise utilizando Pandas.

In [29]:
df = pd.read_csv('../data/Churn_Modelling.csv')

## Visualização Inicial dos Dados

A visualização inicial permite compreender a estrutura das variáveis disponíveis no dataset.

In [30]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [34]:
print(f'Total de linhas: {df.shape[0]}')
print(f'Total de colunas: {df.shape[1]}')

Total de linhas: 10000
Total de colunas: 14

## Ingestão dos Dados no PostgreSQL

Os dados foram enviados para o banco PostgreSQL, criando automaticamente a tabela clientes.

In [31]:
df.to_sql(
    'clientes',
    engine,
    if_exists='replace',
    index=False
)

1000

## Consulta SQL Analítica

A consulta abaixo apresenta uma análise segmentada por país, identificando quantidade de clientes e saldo médio.

In [32]:
query = """
SELECT 
    "Geography",
    COUNT(*) AS total_clientes,
    ROUND(AVG("Balance")::numeric,2) AS saldo_medio,
    ROUND(AVG("Exited")::numeric * 100,2) AS taxa_churn
FROM clientes
GROUP BY "Geography"
ORDER BY taxa_churn DESC;
"""

In [33]:
resultado = pd.read_sql(query, engine)
resultado

  Geography  total_clientes  saldo_medio  taxa_churn
0   Germany            2509    119730.12       32.44
1     Spain            2477     61818.15       16.67
2    France            5014     62092.64       16.15

## Insight Inicial

A análise identificou diferenças relevantes entre os países em relação à taxa de churn dos clientes.

Esse comportamento sugere que fatores regionais podem influenciar diretamente a evasão bancária, justificando análises mais aprofundadas nas próximas etapas do projeto.

## Conclusão da Etapa

Nesta etapa foi construída a camada inicial da solução de dados, contemplando integração entre Python e PostgreSQL, ingestão automatizada do dataset e consultas SQL analíticas.

Com a base estruturada e persistida no banco relacional, os dados estão preparados para as próximas etapas de análise exploratória e modelagem preditiva de churn.