# Hackathon Artemisia Elas+ Tech
## Sistema Inteligente - Bank Customer Churn

### Objetivo do Notebook

Este notebook tem como objetivo realizar o processo de ETL (Extract, Transform and Load) e a persistência dos dados do dataset Bank Customer Churn, integrando Python e PostgreSQL para construção da pipeline inicial do projeto.

### Etapas do Notebook

- importação das bibliotecas;
- configuração da conexão com PostgreSQL;
- criação automatizada do banco de dados;
- extração dos dados a partir do arquivo CSV (Extract);
- validação e preparação da base de dados (Transform);
- ingestão dos dados no PostgreSQL (Load);
- execução de consultas SQL analíticas.

## Importação das Bibliotecas

Nesta etapa foram importadas as bibliotecas necessárias para leitura e manipulação dos dados, conexão com PostgreSQL e execução das etapas iniciais da pipeline do projeto.

In [3]:
import os
from sqlalchemy import create_engine, text
import pandas as pd

## Configuração da Conexão com PostgreSQL

Nesta etapa foi realizada a configuração da conexão entre Python e PostgreSQL utilizando SQLAlchemy, permitindo a integração entre a aplicação e o banco de dados relacional.

In [4]:
senha = os.getenv("POSTGRES_PASSWORD")

In [5]:
engine = create_engine(
    f"postgresql+psycopg2://postgres:{senha}@localhost:5432/postgres"
)

## Criação e Conexão com o Banco de Dados

Nesta etapa foi realizada a criação automatizada do banco de dados PostgreSQL utilizado no projeto. Após a criação, foi estabelecida a conexão com o banco churn_db para armazenamento e manipulação estruturada dos dados.

In [6]:
with engine.connect() as conn:
    conn.execute(text("COMMIT"))

    try:
        conn.execute(text("CREATE DATABASE churn_db"))
        print("Banco criado com sucesso!")

    except:
        print("Banco já existe.")

Banco já existe.

In [7]:
engine = create_engine(
    f"postgresql+psycopg2://postgres:{senha}@localhost:5432/churn_db"
)

## Extração dos Dados a partir do Arquivo CSV (Extract)

Nesta etapa foi realizada a leitura do dataset Bank Customer Churn a partir do arquivo CSV utilizando Pandas, iniciando o processo de ingestão e preparação dos dados para análise.

In [8]:
df = pd.read_csv('../data/Churn_Modelling.csv')

## Validação e Preparação da Base de Dados (Transform)

Nesta etapa foram realizadas validações básicas de qualidade dos dados, incluindo verificação de valores nulos, duplicidades, estrutura das variáveis e dimensão da base, preparando os dados para persistência no PostgreSQL.

In [9]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [30]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [34]:
print(f'Total de linhas: {df.shape[0]}')
print(f'Total de colunas: {df.shape[1]}')

Total de linhas: 10000
Total de colunas: 14

## Ingestão dos Dados no PostgreSQL (Load)

Após as validações e preparação da base, os dados foram carregados no PostgreSQL para armazenamento estruturado e posterior execução de consultas analíticas.

In [31]:
df.to_sql(
    'clientes',
    engine,
    if_exists='replace',
    index=False
)

1000

## Execução de Consultas SQL Analíticas

Nesta etapa foram realizadas consultas SQL para extração de insights relacionados ao comportamento dos clientes e à taxa de churn bancário por país.

In [32]:
query = """
SELECT 
    "Geography",
    COUNT(*) AS total_clientes,
    ROUND(AVG("Balance")::numeric,2) AS saldo_medio,
    ROUND(AVG("Exited")::numeric * 100,2) AS taxa_churn
FROM clientes
GROUP BY "Geography"
ORDER BY taxa_churn DESC;
"""

In [33]:
resultado = pd.read_sql(query, engine)
resultado

  Geography  total_clientes  saldo_medio  taxa_churn
0   Germany            2509    119730.12       32.44
1     Spain            2477     61818.15       16.67
2    France            5014     62092.64       16.15

## Insight Inicial

A análise identificou diferenças relevantes entre os países em relação à taxa de churn dos clientes.

Esse comportamento sugere que fatores regionais podem influenciar diretamente a evasão bancária, justificando análises mais aprofundadas nas próximas etapas do projeto.

## Conclusão da Etapa

Nesta etapa foi construída a camada inicial da solução de dados, contemplando integração entre Python e PostgreSQL, ingestão automatizada do dataset e consultas SQL analíticas.

Com a base estruturada e persistida no banco relacional, os dados estão preparados para as próximas etapas de análise exploratória e modelagem preditiva de churn.